# SITE CONFIGURATION
title: CryptoChainery # your site title
author: VKR
description: > # Meta description of Homepage
  CryptoChainary aims at being a one-stop resource for blockchain and bitcoin technology. My goal 
  is learn and help people learn about blockchain technology which can truly transform certain aspects of the industry
  as we know it. I am always on the lookout for new and interesting applications of blockchain technology - 
  so if you want to exchange ideas or simply get it touch, please send me an email and let's get talking. Thank you!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cryptochainery.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Your Name
  links:
    #- https://twitter.com/BenBalter
    #- https://www.facebook.com/ben.balter
    #- https://www.linkedin.com/in/BenBalter
    #- https://plus.google.com/+BenBalter
    #- https://github.com/benbalter
    #- https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Tutorials', link: '/blockchain-tutorials'}
  - {name: 'Bitcoin Price', link: '/bitcoin-price-chart'}
  - {name: 'Contact', link: '/contact'}
  - {name: 'About', link: '/about'}


tagline: >
  Simplifying blockchain technology and daily updates on the blockchain/bitcoin industry.

#hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: cryptochainery@gmail.com # email for form submission

twitter_username:  # replace with your_twitter_username or comment to remove link from footer
github_username:   # replace with your_github_username or comment to remove link from footer
instagram_username:  # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname:  # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
